apiVersion: apps/v1
kind: Deployment
metadata:
  name: in-memory-http-service-deployment
  namespace: default
  labels:
    app: in-memory-http-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: in-memory-http-service
  template:
    metadata:
      labels:
        app: in-memory-http-service
    spec:
      containers:
        - name: in-memory-http-service
          image: jinxankit/in-memory-http-service:latest
          ports:
            - containerPort: 8080
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "15"]
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
            successThreshold: 1
      terminationGracePeriodSeconds: 45

---
apiVersion: v1
kind: Service
metadata:
  name: in-memory-http-service-svc
  namespace: default
spec:
  selector:
    app: in-memory-http-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: in-memory-http-service-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kvstore-svc
                port:
                  number: 80